### ISSUE TITLE
Write Code Documentation

### ISSUE THREAD

**Issue by Caldas** [Cybermaxs/Redists#1]
Hi @Cybermaxs, thanks for the project. For what I already saw it look like amazing.

I'm facing several problems to understand everything in details (for instance, what are *keyNormalizationFactor* and *dataPointNormalizationFactor* on **TimeSeriesOptions** class) and this could be avoided if main class have the code documentation.

Any chance to get it soon?

**Comment by Cybermaxs** [comment]
Hi, 
Thanks for your feedback.
Xml doc was not generated and not included in the nuget package.
https://github.com/Cybermaxs/Redists/commit/8f01877e416acffd5fdb8728c7826d500f11e85c and  https://github.com/Cybermaxs/Redists/commit/8f01877e416acffd5fdb8728c7826d500f11e85c  will fix this.

The new version is available on nuget.org

**Comment by Caldas** [comment]
Thanks @Cybermaxs ..

*ps:* Good moving changing *DataPoint* **ts** to **timestamp** :smile:
