### ISSUE TITLE
Keys Being Set Without TTL

### ISSUE THREAD

**Issue by TKammerer** [Cybermaxs/Redists#4]
I am creating keys with this client

```
var secondOptions = new TimeSeriesOptions(1000, 1000, TimeSpan.FromMinutes(1), "ts#s");
temp.SecondClient = TimeSeriesFactory.New(_db, key, secondOptions);
```

It is creating keys with no TTL. Is this desired behavior. I would expect every key generated by this client would expire ~1 minute from creation?

![image](https://cloud.githubusercontent.com/assets/3399195/19930912/eb1a67a6-a0e0-11e6-8965-2e4b6b938d1f.png)

**Comment by cybermaxs** [comment]
True !
Thanks for the issue. Fix is included in the lastest nuget.
